baseURL = "https://kaylenpillay.com/"
languageCode = "en-us"
title = "Kaylen Pillay"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  defaultTheme = "light"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about-me/"
    weight = 1

  [[menu.main]]
    identifier = "upcoming"
    name = "Upcoming Releases"
    url = "/upcoming-releases/"
    weight = 2

  [[menu.main]]
    identifier = "short works"
    name = "Short Works"
    url = "/short-works/"
    weight = 2


[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

